notion:
  api_key : <insert_api_key_here>
  databases :
  - <example_database_label_here>:
      id : <insert_id_here>
      description: Description of the database
      output: <insert_output_filepath_here>

google:
  credentials_file: <insert_filepath_here>
  spreadsheets:
  - <example_spreadsheet_label_here>:
      id: <insert_id_here>
      description: Description of the spreadsheet
      input_json: <inser_filepath_to_json_here>
